Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,8 +49,15 @@ jobs:
       shell: bash
       id: get-function
       run: |
-          aws lambda get-function --function-name ${{steps.lambda-function-name.outputs.function-name}} echo "::set-output name=error-code::$?" || echo "::set-output name=error-code::1"
+          
+          { # try
 
+              aws lambda get-function --function-name ${{steps.lambda-function-name.outputs.function-name}} &&
+              echo "::set-output name=error-code::$?"
+
+          } || { # catch
+              echo "::set-output name=error-code::1"
+          }
 
     - name: Now If present, update lambda
       shell: bash
